# Generated by Django 4.2.28 on 2026-02-19 09:40

import core.utils
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        default=core.utils.uuidv7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),
                (
                    "name",
                    models.CharField(help_text="Human-readable title", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description", null=True
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("standalone", "Standalone"),
                            ("extension", "Extension"),
                        ],
                        help_text="Standalone forms create submissions; extensions modify model json_ext",
                        max_length=20,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True,
                        help_text="Model name for extensions (e.g., 'Individual', 'Policy')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        help_text="Full form definition JSON (opaque to BE)"
                    ),
                ),
                (
                    "entry_point",
                    models.CharField(
                        help_text="Standalone: submenu key; Extension: contribution point key",
                        max_length=200,
                    ),
                ),
                (
                    "submit_actions",
                    models.JSONField(
                        blank=True,
                        help_text="ETL mapping, processing pipelines (null for extensions)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Definition",
                "verbose_name_plural": "Form Definitions",
            },
            bases=(
                dirtyfields.dirtyfields.DirtyFieldsMixin,
                core.utils.CachedModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalFormSubmission",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, editable=False
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        db_index=True,
                        default=core.utils.uuidv7,
                        editable=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),
                (
                    "submission_data",
                    models.JSONField(
                        help_text="Raw submitted field values {field_name: value, ...}"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("processed", "Processed"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("date_submitted", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"form_type": "standalone"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="form_builder.formdefinition",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Form Submission",
                "verbose_name_plural": "historical Form Submissions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFormDefinition",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, editable=False
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        db_index=True,
                        default=core.utils.uuidv7,
                        editable=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),
                (
                    "name",
                    models.CharField(help_text="Human-readable title", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description", null=True
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("standalone", "Standalone"),
                            ("extension", "Extension"),
                        ],
                        help_text="Standalone forms create submissions; extensions modify model json_ext",
                        max_length=20,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True,
                        help_text="Model name for extensions (e.g., 'Individual', 'Policy')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        help_text="Full form definition JSON (opaque to BE)"
                    ),
                ),
                (
                    "entry_point",
                    models.CharField(
                        help_text="Standalone: submenu key; Extension: contribution point key",
                        max_length=200,
                    ),
                ),
                (
                    "submit_actions",
                    models.JSONField(
                        blank=True,
                        help_text="ETL mapping, processing pipelines (null for extensions)",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Form Definition",
                "verbose_name_plural": "historical Form Definitions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        default=core.utils.uuidv7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),
                (
                    "submission_data",
                    models.JSONField(
                        help_text="Raw submitted field values {field_name: value, ...}"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("processed", "Processed"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("date_submitted", models.DateTimeField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        limit_choices_to={"form_type": "standalone"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form_builder.formdefinition",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
            },
            bases=(
                dirtyfields.dirtyfields.DirtyFieldsMixin,
                core.utils.CachedModelMixin,
                models.Model,
            ),
        ),
    ]
