# Generated by Django 4.2.28 on 2026-02-20 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="date_valid_from",
            field=models.DateTimeField(
                db_column="DateValidFrom", default=datetime.datetime.now
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="date_valid_to",
            field=models.DateTimeField(blank=True, db_column="DateValidTo", null=True),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="replacement_uuid",
            field=models.UUIDField(blank=True, db_column="ReplacementUUID", null=True),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="date_valid_from",
            field=models.DateTimeField(
                db_column="DateValidFrom", default=datetime.datetime.now
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="date_valid_to",
            field=models.DateTimeField(blank=True, db_column="DateValidTo", null=True),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="replacement_uuid",
            field=models.UUIDField(blank=True, db_column="ReplacementUUID", null=True),
        ),
        migrations.AddField(
            model_name="historicalformdefinition",
            name="date_valid_from",
            field=models.DateTimeField(
                db_column="DateValidFrom", default=datetime.datetime.now
            ),
        ),
        migrations.AddField(
            model_name="historicalformdefinition",
            name="date_valid_to",
            field=models.DateTimeField(blank=True, db_column="DateValidTo", null=True),
        ),
        migrations.AddField(
            model_name="historicalformdefinition",
            name="replacement_uuid",
            field=models.UUIDField(blank=True, db_column="ReplacementUUID", null=True),
        ),
        migrations.AddField(
            model_name="historicalformsubmission",
            name="date_valid_from",
            field=models.DateTimeField(
                db_column="DateValidFrom", default=datetime.datetime.now
            ),
        ),
        migrations.AddField(
            model_name="historicalformsubmission",
            name="date_valid_to",
            field=models.DateTimeField(blank=True, db_column="DateValidTo", null=True),
        ),
        migrations.AddField(
            model_name="historicalformsubmission",
            name="replacement_uuid",
            field=models.UUIDField(blank=True, db_column="ReplacementUUID", null=True),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("processed", "Processed"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("processed", "Processed"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
