# Generated by Django 4.2.28 on 2026-02-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_builder", "0002_formdefinition_date_valid_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdefinition",
            name="entry_point",
            field=models.CharField(
                blank=True,
                help_text="Standalone: submenu key; Extension: contribution point key",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalformdefinition",
            name="entry_point",
            field=models.CharField(
                blank=True,
                help_text="Standalone: submenu key; Extension: contribution point key",
                max_length=200,
                null=True,
            ),
        ),
    ]
